default_agent: adidlabs_agents
agents:
  adidlabs_agents:
    name: adidlabs_agents
    language: python
    node_version: '20'
    entrypoint: /Users/stefanoolivieri/Documents/LAB/adidlabs/agents/entrypoint.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_12
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/stefanoolivieri/Documents/LAB/adidlabs/agents
    aws:
      execution_role: arn:aws:iam::780477232234:role/AmazonBedrockAgentCoreSDKRuntime-ap-southeast-2-258e5892bb
      execution_role_auto_create: false
      account: '780477232234'
      region: ap-southeast-2
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-780477232234-ap-southeast-2
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: false
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: adidlabs_agents-RNC4JGDkbF
      agent_arn: arn:aws:bedrock-agentcore:ap-southeast-2:780477232234:runtime/adidlabs_agents-RNC4JGDkbF
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: adidlabs_agents_mem-knJ5nM5t1n
      memory_arn: arn:aws:bedrock-agentcore:ap-southeast-2:780477232234:memory/adidlabs_agents_mem-knJ5nM5t1n
      memory_name: adidlabs_agents_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
